import { Computer, NetworkCheck, WarningAmber } from "@mui/icons-material";
import { Box, Card, CardContent, Grid2, LinearProgress, Stack, Typography } from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { api } from "../api";

type Device = { id: number; name: string; device_type: string; vendor: string; management_ip: string };
type Summary = { devices: number; connected: number; disconnected: number; open_alarms: number };
function Metric({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <Card><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h4">{value}</Typography></Box>{icon}</Stack></CardContent></Card>; }
export default function DashboardPage() { const devices = useQuery({ queryKey: ["devices"], queryFn: () => api.get<Device[]>("/devices").then((r) => r.data) }); const summary = useQuery({ queryKey: ["monitoring-summary"], queryFn: () => api.get<Summary>("/monitoring/summary").then((r) => r.data) }); const data = summary.data; const count = data?.devices ?? devices.data?.length ?? 0; return <><Typography variant="h4" gutterBottom>Network Overview</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Operational summary for Central Railway MPLS infrastructure</Typography><Grid2 container spacing={2}><Grid2 size={{ xs: 12, md: 4 }}><Metric label="Managed Devices" value={count} icon={<Computer color="primary" fontSize="large" />} /></Grid2><Grid2 size={{ xs: 12, md: 4 }}><Metric label="Connected Devices" value={data?.connected ?? "—"} icon={<NetworkCheck color="success" fontSize="large" />} /></Grid2><Grid2 size={{ xs: 12, md: 4 }}><Metric label="Open Alarms" value={data?.open_alarms ?? "—"} icon={<WarningAmber color="warning" fontSize="large" />} /></Grid2></Grid2><Card sx={{ mt: 3 }}><CardContent><Typography variant="h6" gutterBottom>Monitoring status</Typography><Typography color="text.secondary" variant="body2">Use device polling to refresh CPU, memory, temperature, interface and LLDP data. Dashboard values are based on the latest collected records.</Typography><LinearProgress variant="determinate" value={55} sx={{ mt: 2, height: 8, borderRadius: 4 }} /></CardContent></Card></>; }
